### ISSUE TITLE
No such file or directory: 'data/smpl_mean_params.npz'

### ISSUE THREAD

**Issue by djwayuanle** [leezhongguo/MVSPIN_NEW#1]
I can download and install the necessary environment and data according to the requirements. First, I can't download the. npy file according to the website provided in readme, and I can't find the scrbits in 'dataset / preprocess'. Then when I run the eval.py file according to the requirements in readme, an error occurs: no such file or directory:No such file or directory: 'data/smpl_mean_params.npz' ​I want to know how to get the. npy and. npz files necessary for the program to run.

Then I downloaded [SPIN] according to the website provided in readme. From here, I know 'smpl_mean_params.npz' file is a slit modification of the original. h5 file provided by the [HMR repo]. According to the website provided by readme of [SPIN], download the original .h5 file: 'neutral_ smpl_ mean_ Params.h5', But I don't know how to convert the. h5 file into the .npz file I need. Please let me know. Thank you very much!!

**Comment by minhtcai** [comment]
Hi, I got into this problem, how did you fix this?
